description: "This research project develops training materials for reseachers wanting to learn to build project
websites in GitHub with GitHub Pages."
description2: "This page is simply a demonstration of me following a carpentries course on jekyll pages."
email: "team@carpentries.org"
theme: jekyll-theme-tactile
